### ISSUE TITLE
bug collision detection with a wall wearing an image

### ISSUE THREAD

**Issue by sizvix** [c-frame/aframe-extras#107]
I had a bug with collision detection and a wall when there is an object on it
I made a minimal code with the bug http://www.silpaop.com/VR_physical_bug/
on this example , on the wall on the right , i put an image and the wall loose his collision property

**Comment by donmccurdy** [comment]
Part of the issue is that you can't nest two physics bodies inside one another like this:

``` html
<a-plane class="wall" static-body>
          <a-image src="plan.png" class="image" static-body></a-image>
</a-plane>
```

The outer body will wrap everything inside of it, so it's better just to do this:

``` html
<a-plane class="wall" static-body="shape: box">
          <a-image src="plan.png" class="image"></a-image>
</a-plane>
```

The second issue is that the physics body isn't being rotated to match the wall itself, so that's a bug I'll need to look into.
