### ISSUE TITLE
gltf appears to move differently than COLLADA or a-frame geometries when using universal-controls to move the camera

### ISSUE THREAD

**Issue by hilliardkc** [c-frame/aframe-extras#136]
![gltf-movement](https://cloud.githubusercontent.com/assets/1388620/24381002/fc23abc2-1302-11e7-8d36-c0d5dcf93956.gif)

The green object is a simple a-frame box, the floor and table in front of it are part of a larger gltf model. I'm moving the camera using keyboard controls, but this also happens with checkpoint controls. The shadows are baked on the floor material, that black rectangle should be staying underneath the green box.

**Comment by donmccurdy** [comment]
Hi @hilliardkc — I think that is an issue in THREE.GLTFLoader, that has been fixed (https://github.com/mrdoob/three.js/pull/10851) but hasn't been released in a three.js update yet. If you have the option in your model creation tools, you may want to try using the MaterialsCommon extension (`-k` with COLLADA2GLTF) instead of custom shaders, which should fix it in the meantime.

**Comment by hilliardkc** [comment]
That did the trick, thank you!
