### ISSUE TITLE
Big size ply model won't load

### ISSUE THREAD

**Issue by jues-zz** [c-frame/aframe-extras#148]
Hi, how can I load the model like this?
[world - old.ply.zip](https://github.com/aframevr/aframe-boilerplate/files/986207/world.-.old.ply.zip)

- A-Frame Version: 0.5.0
- Platform / Device: edge or chrome with gtx 1060
- Reproducible Code Snippet or URL:

```

<a-scene>

<a-entity id="entity" ply-model="src: url(world - old.ply)" position="0 0 0" rotation="-90 0 0"></a-entity>

</a-scene>
```

**Comment by donmccurdy** [comment]
Hi @jues — The short answer is, this file is probably too large. 50mb is too much if you're building anything for mobile, and even trying to debug the model on my laptop it's freezing Chrome up. There also is an error in the JS console saying that THREE.PLYLoader failed at some point, but that could be because the model is corrupt, or could be related to memory size.

You would be able to reduce the total file size by converting to formats like glTF or Draco. But that won't change the total number of vertices, which is still very high, so if you're targeting any mobile VR stuff that's still too much.

The more practical solution would be to simplify the model, before trying to import it. There are automatic ways to do this, like the [Decimate Modifier](https://docs.blender.org/manual/es/dev/modeling/modifiers/generate/decimate.html) in Blender.

**Comment by jues-zz** [comment]
Sorry, the model is a bit corrupt, it has many useless extra face lines.
After I remove that, it displays normally.
