### ISSUE TITLE
Enabling touch&drag to rotate scene in Mobiles

### ISSUE THREAD

**Issue by venkatapathy** [c-frame/aframe-extras#151]
Hi,

When we add universal controls to the camera component, WASD controls are enabled for movements in Desktop view and touch for movements in Mobile. To rotate the scene, in mobile view the only option is to physically rotate the mobile. Whereas in the default camera, touch&drag is used to rotate the screen. Is it possible to enable touch&drag for rotating the screen along with touch for movement for the mobile view?

**Comment by donmccurdy** [comment]
Hi @venkatapathy — The `universal-controls` component is a wrapper around several different controls components, for HMD, touch-to-move, keyboard, gamepad, etc... Currently none of those support touch&drag, but it is designed so that you can add your own component to extend `universal-controls`' capabilities. There's very limited documentation on this [here](https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#usage), and I will try to write up better documentation for custom controls in the coming week or two.

**Comment by venkatapathy** [comment]
Ok. Thank you so much for the guidance. Will take a look at it! :+1:
