### ISSUE TITLE
question: what format/struct is the json (for json-model) like?

### ISSUE THREAD

**Issue by creeperyang** [c-frame/aframe-extras#153]
Currently I have a json like below:

```JS
{
	"metadata": {
		"version": 4.5,
		"type": "Geometry",
		"generator": "Geometry.toJSON"
	},
	"uuid": "805B4F60-A072-4368-9856-184C2E99137A",
	"type": "Geometry",
	"data": {
             "vertices": [],
             "normals": [],
              "faces": []
        }
}
```

The json could not fit `json-model`, and when I extract `data` as the content for `json-model`, still not work.

```JS
// fails because materials is undefined
loader.load(data.src, function (geometry, materials) {

      // Attempt to automatically detect common material options.
      materials.forEach(function (mat) {
```

SO, what the correct format?

**Comment by donmccurdy** [comment]
Hi @creeperyang — `json-model` uses THREE.JSONLoader, and `object-model` uses THREE.ObjectLoader. Both use three.js's own JSON format, in slightly different forms. I'm not an expert on that format, and the format has changed over time, so I can't tell if your JSON is correct just by looking at it. If `json-model` doesn't work, I would suggest trying `object-model` instead.

If neither is working, do you know if the geometry is loading correctly? Or are both materials and geometry missing? To move forward, you may need to either send a PR or provide a complete model example so that I can debug.

**Comment by creeperyang** [comment]
@donmccurdy Thanks and I'll have a try.

**Comment by creeperyang** [comment]
I checked <https://github.com/rexraptor08/animation-controls>, and change my model to:

```js
{
	"metadata": {
		"version": 4.5,
		"type": "Geometry",
                "uuid": "805B4F60-A072-4368-9856-184C2E99137A",
	        "type": "Geometry",
		"generator": "Geometry.toJSON"
	},
         "vertices": [],
         "normals": [],
         "faces": [],
         "materials": [] // copied from animation-controls
}
```
Finally it works, although the material is not what I want.
