### ISSUE TITLE
glTF alphaMode on 3.10.0 not working

### ISSUE THREAD

**Issue by DudeGrim** [c-frame/aframe-extras#168]
Hello! With 3.10.0, its seems to have made alphaMode on glTF models become ignored. Worked fine on 3.9.1 before. I have not changed the model if anything, I noticed that Three.js got updated. Maybe something related along those lines?

**Comment by donmccurdy** [comment]
Hi @DudeGrim — With 3.10.0, I rolled back to GLTF2Loader from three.js r86, rather than hotloading the newest version from the `dev` branch. This was intentional, as I wanted to match the version that we expect to ship with A-Frame 0.7.0, but we do lose out on some more recent fixes.

If you need a recent or custom version of the loader, I'd suggest downloading [GLTFLoader.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js) directly from threejs, and including it in your page, then adding a custom component:

```js
AFRAME.registerComponent('gltf-model-custom', {
  schema: {type: 'model'},

  init: function () {
    this.model = null;
    this.loader = new THREE.GLTFLoader();
    this.loader.setCrossOrigin('Anonymous');
  },

  update: function () {
    var self = this;
    var el = this.el;
    var src = this.data;

    if (!src) { return; }

    this.remove();

    this.loader.load(src, function gltfLoaded (gltfModel) {
      self.model = gltfModel.scene;
      self.model.animations = gltfModel.animations;
      el.setObject3D('mesh', self.model);
      el.emit('model-loaded', {format: 'gltf', model: self.model});
    });
  },

  remove: function () {
    if (!this.model) { return; }
    this.el.removeObject3D('mesh');
  }
});
```

three.js recently renamed GLTF2Loader to GLTFLoader (and removed the old GLTFLoader), hence the inconsistency in the names. This is also why `gltf-model-next` 3.9.1 is not working now, because hotloading from the `dev` branch gets a 404. So better to stick with a locked version. :)

**Comment by DudeGrim** [comment]
Thanks @donmccurdy ! That gave the model the alpha back. Model is normal again, your work around works.
