### ISSUE TITLE
Add state events to checkpoint-controls

### ISSUE THREAD

**Issue by paulocf92** [c-frame/aframe-extras#171]
Right, I absolutely love how this component works and I'm trying to employ some things on top of it, so here's my second request: could you please emit an event so we can catch when a checkpoint-controls animate event started, and when it finished? You could go as far as creating intermediary events returning how much time in secs have elapsed since it started moving, but that's absolutely not a need I have (and I think nobody would ever).

So, yeah, an event to track on-start and another for on-end. I'm trying to create [some sort of notification](https://github.com/valento92/aframe-basic-scene/issues/3) in a visible way and this would simplify many things.

**Comment by paulocf92** [comment]
Actually it's not necessary to track movement type either (teleport, animate), if you default to having these events when they occur, then it would be perfect.

**Comment by donmccurdy** [comment]
Good idea! Added `navigation-start` and `navigation-end` events (which will be fired together in the case of teleporting). Event details include `event.detail.checkpoint`, so you could check distance to that before each frame if you wanted to show progress. Didn't want to do separate progress events, because events on each frame can be not-great for performance.

**Comment by paulocf92** [comment]
I might've gotten it wrong, because it's not working for me (disregard the fiddle permission and move the mouse+click to see):
https://jsfiddle.net/9wfcLdf4/

**Comment by donmccurdy** [comment]
Event will fire on the player (or whatever has `checkpoint-controls`), not the checkpoint itself - `event.detail.checkpoint` would be the checkpoint element.
