### ISSUE TITLE
Physics - prevent kinematic-body from dropping too far down?

### ISSUE THREAD

**Issue by edent** [c-frame/aframe-extras#186]
I'm prepared to be told that I'm doing something daft!

I want to build a staircase.  In this example, I can walk forward and the camera position climbs with the stairs.  If I step backwards, the camera position drops. All good.

But if I try to walk up again, I can't!

When the scene is loaded, the Y position of the entity is `1.674`, after climbing the stairs it rises successfully. When I walk backwards off the stairs, the position drops to down to `0.707`.  

This seems to confuse the physics engine, and on walking forward I can no longer climb upwards.

Here's some sample code

```
<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v3.12.4/dist/aframe-extras.min.js"></script>  </head>
<body>
	<a-scene physics>
		<!-- Player -->
		<a-entity
			camera="userHeight: 1.5"
			universal-controls
			kinematic-body>
		</a-entity>

		<!-- Ground -->
		<a-grid static-body></a-grid>

		<!-- Obstacles -->
		<a-box
			color="#f00"
			width="3" height="0.5" depth="1" 
			position="0 0 -3"
			static-body>
		</a-box>
		<a-box 
			color="#0f0"
			width="3" height="1" depth="1" 
			position="0 0 -4"
			static-body>
		</a-box>
		<a-box
			color="#00f"
			width="3" height="1.5" depth="1" 
			position="0 0 -5"
			static-body>
		</a-box>
		<a-box
			color="#0ff"
			width="3" height="2" depth="1" 
			position="0 0 -6"
			static-body>
		</a-box>
		<a-box
			color="#f0f"
			width="3" height="2.5" depth="1" 
			position="0 0 -7"
			static-body>
		</a-box>
		<a-box
			color="#fff"
			width="3" height="3" depth="1" 
			position="0 0 -8"
			static-body>
		</a-box>
		<a-box
			color="#000"
			width="3" height="3.5" depth="1" 
			position="0 0 -9"
			static-body>
		</a-box> 
	</a-scene>
```

Any ideas on how I prevent this happening?

**Comment by donmccurdy** [comment]
Thanks for the concise reproducible demo on this. You're not doing anything incorrectly here — the `kinematic-body` component is experimental precisely because of issues like this. One way to work around it is to place a single diagonal, invisible `static-body` along the length of the stairs, and remove `static-body` from the steps themselves. Walking up is smoother, and less likely to run into edge cases.

But generally I'm not very happy with using physics for player navigation, and have been planning to encourage use of nav meshes instead. See: https://github.com/donmccurdy/aframe-extras/issues/161. Unfortunately `universal-controls` does not yet support nav meshes, that's in progress.

**Comment by donmccurdy** [comment]
Next release will support using a nav mesh as the "ground" with `universal-controls`.
