### ISSUE TITLE
kinematic-body and networked-aframe body position problem 

### ISSUE THREAD

**Issue by arpu** [c-frame/aframe-extras#197]
a kinematic-body on a plane get always a body position change
-> many network webrtc sends  

if its needed i can make a small test sample

**Comment by donmccurdy** [comment]
Anything object with physics is going to get position/rotation updates on every frame, so I think changes within both libraries will be needed to make them work together. There is an #naf-physics room in Slack where you could perhaps get updates on how things are going.

But generally I'm trying to replace `kinematic-body` with navmesh-based controls, so that physics isn't needed at all for player  movement.
