### ISSUE TITLE
Mouse controls rotating a certain way quickly causes jerking back motion

### ISSUE THREAD

**Issue by GrandmasterGrogu** [c-frame/aframe-extras#205]
I'm not exactly sure how to describe this. The mousecontrols sometimes will create a "jerking back" motion in a scene. I'm using Chrome.

For instance, this dog scene moving up or to the left quickly seems to do that.
https://webvr.donmccurdy.com/animation/
Going back to the standard aframe mouse control (without extras), I do not observe the jerking motion.

**Comment by donmccurdy** [comment]
I can't seem to reproduce this; would you be able to record a screencap? Also curious, are you using a standard mouse, or a trackpad?

**Comment by EvieMarie** [comment]
I'm updating to a new server and am experiencing this "bounce-back" as well.  Ubuntu 17.04.  Will work on getting a screen capture for you.  In the meantime, to describe:

Forward, backward, and side to side motion seems to operate properly.

However, when rotating in MouseLook, the scene bounces back so that the building in front of me continues to be in the screen.  

Will try returning to standard mouse controls myself to see if the issue persists.

**Comment by EvieMarie** [comment]
https://i.gyazo.com/0b52a27bffb1f6137da503ba8edae96f.gif

Even though I am steadily using my mouse to rotate, you can see the screen bounces back.  I can also confirm that returning to standard [camera look-controls wasd-controls] does not have the same issue.  I do love the universal controls, though, thank you for your great work.  Hope this helps find a solution.

Update -- Video was taken on Chrome.  Further testing shows that Firefox is not experiencing same issue. Thanks again!

**Comment by EvieMarie** [comment]
Must have something to do with a Chrome update.  I thought it was only affecting the new server, but appears to be happening across the board.  You can see this issue in action at https://web-worldz.com, just log in as Guest for easy entrance.   Once again, Firestorm still operating well.

**Comment by donmccurdy** [comment]
Hm, I still can't reproduce this but I notice you're using an `<iframe>` on the https://web-worldz.com/ example. I think the meltdown/spectre changes have caused a lot of weird bugs, especially with iframes, because of the "strict site isolation" thing that had to be enabled. Hoping that Chrome will address that soon...

**Comment by EvieMarie** [comment]
Thanks for responding. We are using Iframes in that particular live page, but the problem persisted in the world loading without an iframe, as presented in the .gif above.  While iframes create possible other issues, don't think that is causing this one.  Assuming this is on Chrome's doorstep.  Have had multiple testers and complaints and everyone surveyed experienced the same problem.  

We are now recommending our users move to Firefox.  We also found the previous Chrome update caused audio issues for a mac users. In agreement on hoping Chrome addresses soon.

**Comment by EvieMarie** [comment]
Follow up:  Google Chrome updated again. Version 64.0.3282.119 fixed the issue broken by their previous update as described above. Thanks again for taking the time to check the issue and respond!

**Comment by donmccurdy** [comment]
Ok, glad it's working again! 🙂
