### ISSUE TITLE
[kinematic-body] Teleportation script has stopped working with latest version of aframe-extras.js

### ISSUE THREAD

**Issue by bizzell** [c-frame/aframe-extras#246]
Hi.
I have a very simple teleport script designed to move a kinematic-body 'player' to a random location if there is a collision with a specified object. It worked fine with an older version of aframe-extras.js. since i updated to the latest version 4.1.2 it has stopped working and i have no idea why?

The javascript function for teleporting the player object:
```
function teleport(event) {
        var target = event.currentTarget;
        if(event.detail.body.el.className === "telepad"){
            posX = Math.floor((Math.random() * 40) + -20);
            posZ = Math.floor((Math.random() * 40) + -20);
            target.setAttribute("position", {posX: 0, y: 1.5, z: posZ});
            console.log('posX ' + posX);
            console.log('posY ' + posZ);
            console.log(event.detail.body.el.className);
            console.log(target.getAttribute("position"));
        }
        
    }
```
The html for the player object:
```
<a-entity id="player" movement-controls kinematic-body position="">
        <a-entity id="camera"
                  camera
                  position="0 1.6 0"
                  look-controls="pointerLockEnabled: true"
                  progressive-controls="objects: [grabbable], [droppable], [clickable]; gazeMixin: gazer; pointMixin: pointer; touchMixin: ctrlr">
                    <a-entity cursor position="0 1.6 -1"><!--position adjusts vertical offset caused by "Y" position for kinematic body-->
                    </a-entity>
        </a-entity>
      </a-entity>
```

Any help appreciated
Thanks.

**Comment by donmccurdy** [comment]
Can't think of an obvious reason, but could you try:

1. instead of `setAttribute('position', ...)` use `el.object3D.position.set(x,y,z)`
2. the position `y` value should probably be 0 now, since latest version of A-Frame handles the offset automatically
3. are you also using a recent version of aframe-physics-system? it's not bundled with aframe-extras automatically in the last version


if that doesn't work, could you share a demo?

**Comment by bizzell** [comment]
Hi.
I've just been revisiting the teleport script with the 3 points you raised in mind...

1. el.object3D.position.set(x,y,z) -  do not help.
2. Thanks for the info about the offset.
3. I'm using aframe-physics-system version 3.2.1 (aframe version 0.8.2; aframe-extras 4.1.2; aframe-event-set-component version 4.0.0).

The script works fine if I change it so that the telepad changes position rather than the player entity.
I've put and example here:
https://codepen.io/beebabba/pen/vaNmxX

Thanks again.

**Comment by donmccurdy** [comment]
Ok, it looks like the issue is that to move the player (or a dynamic physics object in general) you need to reposition its `el.body`. For example:

```js
el.body.position.set(posX, 1.5, posZ);
```

This is because the object's position is overwritten with its position in the physics simulation on each frame, so you need to modify the physics simulation.

**Comment by bizzell** [comment]
Hi Don.

 

Thanks for taking time to look at this. I have moved on from that particular project, but the answer to that project may well be very useful in solving another similar issue I’ve come up against while using Orbit Controls.

 

Regards.

Bis.
