### ISSUE TITLE
[movement-controls]: inconsistencies between Gear VR and Go

### ISSUE THREAD

**Issue by dsinni** [c-frame/aframe-extras#280]
I've noticed some inconsistencies between Gear VR and Oculus Go in `movement-controls`.

When using A-Frame `0.8.2`, Oculus Go controls let you move forward, backward, and strafe side to side; this is not true for Gear VR, which only seems to let you move forward and backward.

When using A-Frame `master` (`826e983d989312fe7cd75b9cc92e58b7a5cc195f`), Oculus Go controls seem to still work as expected, but Gear VR does nothing.

I'm not sure if this is related, but I've also noticed that forward/up often and sporadically stops registering on the Go, in both the A-Frame `master` and `0.8.2`. However, I'm not sure if that's more of an issue with the `oculus-go-controls` component itself, as the trackpad also stops highlighting when touching that region (or it could be an issue with my controller, specifically).

Feel free to use this as a demonstration: https://bunker-baked.glitch.me/

Fork at will: https://glitch.com/~bunker-baked

**Comment by donmccurdy** [comment]
Hm unfortunately I don't have access to a GearVR... would you want to try a PR for this?

**Comment by dsinni** [comment]
Yeah, I can take a stab at it. Thanks.

**Comment by vincentfretin** [comment]
I'm closing old issues, the issue may have been fixed in recent build, please try https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@501d66b/dist/aframe-extras.min.js you can reopen if it's still an issue with aframe master and latest aframe-extras build.
Please note that both Gear VR and Oculus Go are unmaintained products now. Oculus browser wasn't updated there for a long time now.
