### ISSUE TITLE
[movement-controls]: Go Trackpad locks up under the Oculus Browser

### ISSUE THREAD

**Issue by andrewaxelrod** [c-frame/aframe-extras#286]
When **movment-controls** is used within an anti-aliasing scene, the Oculus Go controller locks up. I do know antialias causes a lot of slow downs.

**Steps**
- [ ] Test using Oculus Go Headset.
- [ ] Go to https://high-airport.glitch.me/
- [ ] Move around for 5-10 minutes. There seems to be a memory leak as the entities, plane, and movement becomes choppy.
- [ ] Eventually, the Oculus Go controller fails to move in one one or more directions. 

Device: Oculus Go
Browser: Oculus Browser
Version: 3.55.12
Runtime Version: 3.7.3
Code Base:  https://high-airport.glitch.me/
A-Frame: 0.8.2
A-Frame Extras: 5.0.0

**Comment by donmccurdy** [comment]
> Move around for 5-10 minutes. There seems to be a memory leak as the entities, plane, and movement becomes choppy.

That's a pretty long repro step :/ does this only happen when `movement-controls` trackpad is involved? Not, for example, using just `look-controls` or the `checkpoint` functionality of `movement-controls`?

> Eventually, the Oculus Go controller fails to move in one one or more directions.

Hm, you mean for example you might be able to move forward and right, but not left?

**Comment by dsinni** [comment]
> That's a pretty long repro step :/ does this only happen when movement-controls trackpad is involved? Not, for example, using just look-controls or the checkpoint functionality of movement-controls?

I have seen this also. In my experience, it only appears to be when using the trackpad and it becomes difficult to move in one direction, often being forward, but not consistently. Sometimes, the functionality can be restored, but it is sporadic. I haven't been able to reproduce the bug at will, but it does happen quite often.

> Hm, you mean for example you might be able to move forward and right, but not left?

Yeah, pretty much, but it's usually forward in my experience.

It may be that it happens when the scene is slightly too demanding, but it's odd that some directions would work as expected while others would not.

**Comment by dsinni** [comment]
Still experiencing this. :(

**Comment by paulmasson** [comment]
There is a known hardware bug in the Oculus Go controller at the top of the touchpad:

https://developer.oculus.com/bugs/bug/470815390013567/
https://forums.oculusvr.com/developer/discussion/66821/oculus-go-controller-touchpad-issues-discussion

That would affect forward movement.

**Comment by vincentfretin** [comment]
I'm closing the issue. Oculus Go is an unmaintained product now.
