### ISSUE TITLE
No positional tracking on DK2 with universal-controls

### ISSUE THREAD

**Issue by georational** [c-frame/aframe-extras#57]
Somehow only rotation works here :)

**Comment by donmccurdy** [comment]
Coming soon, I expect this to land with A-Frame v0.3.0 but possibly earlier. :)

**Comment by georational** [comment]
thanks. good to know

**Comment by donmccurdy** [comment]
Positional tracking is in now – aframe-extras/v2.1.0 and up. Note that v2.\* is compatible with A-Frame master (and will work with aframe/v0.3.0 when it's released) but not with older versions of A-Frame.

Positional tracking also doesn't work with `kinematic-body`, but that's somewhat intentional – stopping the camera when the player tries to step through a wall would be jarring, and I'd want to see a good example before trying it (better to just make the scene appropriately sized).
