### ISSUE TITLE
Support rotation control from touch input

### ISSUE THREAD

**Issue by allanweir** [c-frame/aframe-extras#65]
It would be really useful if the 'rotationControls' of universal-controls allowed support for touch-control too. The use-case is when inside a video sphere and you just want to rotate the camera rather than move through the physical space. Currently when trying to use touch for rotation I receive an error.

`TypeError: control.isRotationActive is not a function. (In 'control.isRotationActive()', 'control.isRotationActive' is undefined)`

**Comment by donmccurdy** [comment]
Hi @allanweir – I don't plan to include touch-rotation as a default, since more VR-friendly navigation is time consuming already, but a goal of `universal-controls` is that you can add your own controls components as needed, and they'll 'just work' with the existing ones. For example, to make a `custom-controls` component that does what you describe:

``` html
<a-entity camera universal-controls="rotationControls: hmd, gamepad, custom" />
```

``` javascript
AFRAME.registerComponent('custom-controls', {
  isRotationActive: function () { /* ... */ },
  getRotationDelta: function () { /* ... */ }
});
```

The code for the component would be _almost_ identical to [mouse-controls](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/mouse-controls.js), except that in `addEventListeners()` you'd want to listen for `touchstart` / `touchend` instead of (or in addition to) `mousedown` / `mouseup`.

This extensibility, and a similar way of adding new controls, will probably be added to A-Frame core in v0.4.0.

**Comment by allanweir** [comment]
Hi @donmccurdy sure that makes sense. If I was to develop that control would you want a pull request or just prefer to keep it separate?

**Comment by allanweir** [comment]
If you would like to keep it separate I've uploaded it to git and npm and is ready for use https://github.com/allanweir/aframe-touch-rotation-controls 

Thanks for the help!

**Comment by donmccurdy** [comment]
Nice job, the component looks good! 

In A-Frame v0.4.0, there will likely be a controls registration API:

``` javascript
AFRAME.registerControls('custom-controls', {
   /* ... */
})`)
```

...very similar to how `universal-controls` works here. [PR#1248](https://github.com/aframevr/aframe/pull/1248). When that lands, I'll remove `universal-controls` and update all of my controls components to use that API. In the meantime I'm not planning to make any big changes, so from my perspective a separate component makes most sense now.

Thanks!

**Comment by donmccurdy** [comment]
@germanviscuso if you mean rotating a model like in [this example](https://threejs.org/examples/?q=gltf#webgl_loader_gltf), this package is probably not what you want. I'd try aframe `orbit-controls`: https://github.com/tizzle/aframe-orbit-controls-component
