### ISSUE TITLE
threemodel.js trigger on a-animate

### ISSUE THREAD

**Issue by msj121** [c-frame/aframe-extras#82]
Is there a way to add to the json loader, to allow a-animate to trigger the "playAnimation" code, but also allow to specify the specific animation in the "<a-animate>"? I think this would allow a lot more usage of the json model.

**Comment by donmccurdy** [comment]
This would be cool, but I think `a-animate` would need changes to support this since it's more designed to animate individual properties. I'm not sure if that really makes sense to add. @ngokevin ?

Maybe it would make more sense to trigger animation with an event, since I assume that's how you're triggering `a-animate` as well?

**Comment by msj121** [comment]
The reason for using a-animate, would be to allow using all the built in functionality.

I think a-animate can trigger custom events... Really all this would mean is the same solution your describing except that the event wouldn't be onmousedown etc... it would be a playEvent that is triggered in a-animate which is in turn triggered by a mouse/gaze. It simply decouples code I think in a good way and leverages the existing coding of a-animate. I'll double check this

**Comment by donmccurdy** [comment]
Thing is I don't think there's any applicable built-in functionality yet, `a-animate` just waits for an event and then tweens HTML properties, whereas we want to wait for an event and then morph the mesh. Listening for the mouse/gaze events is trivial, so there's nothing to reuse there.

That, and I'd want to see this behave similarly with `collada-model` and `gltf-model` rather than having a different animation scheme for different model types.

**Comment by msj121** [comment]
After looking at the a-animate code, it does appear to be primarily a TWEEN wrapper...

The second point of having a similar scheme that is decoupled from the modelling was where I was coming from by using a-animate; however, it is not what I had thought underneath.

What are your thoughts for standardizing the coding methodology? Models listen for a standard play/pause event that has an argument for track for example?

**Comment by donmccurdy** [comment]
I would like to see a common animation manager, maybe even in A-Frame core. Syntax ideas:

Explicit event:

```
<a-entity foo-model="src: ganondorf.foo"></a-entity>

el.emit('playanimation', {name: 'attack'});
```

Custom trigger:

```
<a-entity foo-model="src: ganondorf.foo"
          animation-trigger__1="on: keypress; filter: {code: KeyQ}; name: attack"
          animation-trigger__2="on: keypress; filter: {code: KeyG}; name: dance"></a-entity>
```

But animation APIs have a lot of features; for complex animation sequences you'd might want a programmatic API instead of declarative syntax or events. I'd like to discuss and land a PR on the core `collada-model` first maybe, and then replicate that for other models: https://github.com/aframevr/aframe/issues/1446

**Comment by donmccurdy** [comment]
Going to close this: I do think a general animation manager will need to be built eventually. It would be easier if glTF/JSON/Collada shared the same animation system in THREE.js, which they currently don't. Probably needs to be a separate component, though, and not built into one of the loaders. There's some discussion in the THREE.js (issue 9922) and A-Frame. This is probably the best place for discussion: https://github.com/aframevr/aframe/issues/1446
