### ISSUE TITLE
Passing through floor when dropping from high altitude

### ISSUE THREAD

**Issue by jpatrickpark** [c-frame/aframe-extras#99]
This is something I experience on http://drawvr.com/

When I jump 35+ times and drop straight to the floor, which is 
`a-entity static-body geometry="primitive: plane;"`
I fall through the floor and drop endlessly.

I reproduced this bug once by jumping merely twice or three times, but it is unusual.

**Comment by donmccurdy** [comment]
Hi @jpatrickpark – the main issue is one that is common to many physics engines, and all of the JS physics implementations. Collisions are detected at each frame, so if you're moving fast enough — and if an obstacle is thin enough — you can "skip" through a barrier between frames, as there's no frame where the collision is detectable. This project uses Cannon.js, and they've discussed it [here](https://github.com/schteppe/cannon.js/issues/202).

There are global fixes, e.g. Continuous Collision Detection (CCD), but they're difficult to implement and I'm not sure about performance. Cannon.js has so far not done this.

In particular cases where it's an issue, like this, there are a few ways to work around it:
1. Increase framerate of physics simulation (it doesn't need to match render framerate). Performance makes this _not_ ideal for VR.
2. Increase size of the barrier. For example, use a thick block rather than a plane for the floor.
3. For easy-to-detect collisions (like `position.y <= 0`) add a custom check to make sure the player doesn't fall beneath the floor.

Between the last two, it's usually possible to tune things and avoid issues.

**Comment by donmccurdy** [comment]
In this specific case (if you were building a scene like DrawVR's) I would actually suggest not using physics or jumping animations on the player camera in VR. My `kinematic-body` component kind of sets a bad precedent, and I'm planning to discourage that a bit more actively soon. For non-VR applications it's fine, but in VR it's quite uncomfortable (and incompatible with room-scale navigation).
